controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

formation_index:
    path: /formations
    controller: App\Controller\FormationController::index

formation_show:
    path: /formations/{id}
    controller: App\Controller\FormationController::show

test_prerequis:
    path: /formations/{formation_id}/test
    controller: App\Controller\TestPrerequisController::test

inscription_new:
    path: /inscription/{session_id}
    controller: App\Controller\InscriptionController::new

contact:
    path: /contact
    controller: App\Controller\ContactController::contact
